### ISSUE TITLE
Extensions should not be dropped and should have an attempted upgrade in a try/catch

### ISSUE THREAD

**Issue by autumnjolitz** [djrobstep/migra#113]
This got generated when comparing a new postgres 11 database to an older postgres 10 database. The older database only supports citext version 1.5.

```
create extension if not exists "citext" with schema "public" version '1.5';
drop extension if exists "citext";
```

Dropping the extension is disastrous in nearly every context where the extension is actually used. 

Perhaps something like:

```
ALTER EXTENSION $extension_name TO SCHEMA $schema
;
DO
$do$
BEGIN
  ALTER EXTENSION $extension UPDATE TO '$version';
EXCEPTION
    WHEN invalid_parameter_value THEN
        RAISE NOTICE '% %', SQLERRM
END;
$do$;
```

Would work better?

I currently wrote a quick preprocessor to comment out any statements with `drop extension` in them 🤣

**Comment by djrobstep** [comment]
Thanks for filing this! It's been on the to-do list for a while, to fix this up. There ought to be an option for ignoring the extension version as well (could even be the default, as in most cases, people don't care).

**Comment by djrobstep** [comment]
This is now fixed - alters are now used instead of drop/recreate for extension version changes.
