### ISSUE TITLE
commit lockfile

### ISSUE THREAD

**Issue by SKalt** [djrobstep/migra#118]
>  You should commit the poetry.lock file to your project repo so that all people working on the project are locked to the same versions of dependencies
>  -- [poetry docs, "installing without poetry.lock"](https://python-poetry.org/docs/basic-usage/#installing-without-poetrylock)

Any reason poetry.lock is `.gitignore`'d? If not, this one's pretty simple to fix / a good first contribution.

**Comment by djrobstep** [comment]
I personally like not having it there so that the build installs the latest available dependencies each time, and thus checks it's not broken using the latest available deps.

I realize this is probably frowned upon by some tho as it means builds aren't as repeatable.

**Comment by SKalt** [comment]
You can get the best of both worlds by committing the lockfile and running [`poetry update`](https://python-poetry.org/docs/basic-usage/#updating-dependencies-to-their-latest-versions) to update to the latest versions that your pyproject.toml allows.

**Comment by tad-lispy** [comment]
Hi again!

I'm trying to prepare a Nix derivation for Migra and nondeterministic builds are causing friction. So I second the @SKalt proposition to commit the lock file.

**Comment by djrobstep** [comment]
Done!

**Comment by tad-lispy** [comment]
Thank you :grin:

**Comment by jaredramirez** [comment]
@tad-lispy Did you get your nix derivation working? If so, is it possible to share it?

**Comment by tad-lispy** [comment]
@jaredramirez perhaps you will find this helpful: https://discourse.nixos.org/t/preparing-a-nix-flake-for-a-python-program-migra-using-poetry/12030/9
