### ISSUE TITLE
How to run migra from cloned repo?

### ISSUE THREAD

**Issue by tolmacevalexandr** [djrobstep/migra#119]
I create a fork of migra & schemainspect repositories. I made some useful changes in it. But I don't understand how to run that upgraded migra... Where is entry point?
I see `def do_command():`, it looks like a entry point but where is the function call?

Yes, I can create main.py :
```
from migra.command import do_command
do_command()
```
but how did it work without it before?

And then I get the error:
```
from schemainspect import DBInspector, get_inspector
ImportError: cannot import name 'DBInspector' from 'schemainspect' (unknown location)
```
How to link (reference) to module 'schemainspect' cloned to another dir?
(Sorry, I'm new to python)

**Comment by tolmacevalexandr** [comment]
I wrote a script `run_migra.py` that runs the migra from cloned repos:
```
import sys
from os.path import expanduser

projects_path = expanduser("~") + "/projects/"

migra_path = projects_path + "migra/"
schemainspect_path = projects_path + "schemainspect/"
#print ("migra_path: " + migra_path)
#print ("schemainspect_path: " + schemainspect_path)

sys.path.append(migra_path)
sys.path.append(schemainspect_path)

from migra.command import do_command
do_command()
```
Check that the `projects_path` is correct for you;
and put this `run_migra.py` to appropriate folder (for example `...\Programs\Python\Python38\Scripts\`)

At the first run, you may need to install several additional packages.
For example `pip install sqlbag`.

Surprisingly, I can't rename the script to `migra.py`. This leads to errors...

**Comment by djrobstep** [comment]
Do you have `poetry` installed? Both migra and schemainspect use poetry to manage this stuff.

To run commands in a poetry project you prefix the command with `poetry run`, eg `poetry run migra ...`.

To install a cloned dep from a local path, you can specify that in the pyproject file, eg change the line `schemainspect = "..."` to `schemainspect = {path="../schemainspect"}` or similar.

Let me know if that helps. 

I really appreciate your PRs btw, I am really busy at the moment but will try to get them reviewed and merged as soon as I can!

**Comment by tolmacevalexandr** [comment]
> Do you have `poetry` installed?

Now I installed  `poetry`, then I changed `pyproject.toml`: `schemainspect = {path="../schemainspect"}`. And then I run `poetry install`.
OK, now I can run migra by `poetry run migra ...` only from migra project folder. But I expected to get a `migra.exe` file in my `...\Programs\Python\Python38\Scripts\` that would allow me to run the program simply typing `migra ...` at any directory...

**Comment by djrobstep** [comment]
Poetry will only work within the project folder, but if you `pip install -e path/to/migra` you should be able to run the command from anywhere.

**Comment by tolmacevalexandr** [comment]
> if you `pip install -e path/to/migra` you should be able to run the command from anywhere.

```
C:\Users\atolmachev> pip install -e projects\migra
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: C:\Users\atolmachev\projects\migra
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)
```

**Comment by djrobstep** [comment]
This blog post describes a placeholder `setup.py` file you can create in order to make editable installs work: https://snarky.ca/what-the-heck-is-pyproject-toml/

**Comment by djrobstep** [comment]
Closing this for now, if you have any further questions just ask :)
