### ISSUE TITLE
Dropping views destroys triggers, which aren't recreated

### ISSUE THREAD

**Issue by cyclotron3k** [djrobstep/migra#120]
Testing with Postgres 10, Python 3.7.4, migra 1.0.1575954682

Imagine a view, defined in two schemas but slightly different. When running migra over these two schemas, I've found that the SQL it produces will sometimes just replace the view, and sometimes drop then recreate the view. I'm not sure what causes the difference, but I'm sure there's a good reason. I know that I can cause the drop/create scenario by altering the number of columns in the view.

The problem is that when you drop a view, any dependent triggers are silently dropped too, and are not recreated in the produced SQL.

Base schema:
```SQL
CREATE TABLE "my_table" (
    "some_text" text,
    "some_count" int
);

CREATE VIEW "view_on_table" AS
SELECT some_text, some_count FROM my_table;

CREATE OR REPLACE FUNCTION my_function()
    RETURNS trigger
    LANGUAGE plpgsql
AS $function$
    BEGIN
        INSERT INTO my_table (some_text)
        VALUES (NEW.some_text);
        RETURN NEW;
    END;
$function$
;

CREATE TRIGGER trigger_on_view INSTEAD OF
INSERT ON view_on_table
FOR EACH ROW EXECUTE PROCEDURE my_function();
;

INSERT INTO view_on_table VALUES ('this is a test')
```

Target schema:
```SQL
CREATE TABLE "my_table" (
    "some_text" text,
    "some_date" timestamp,
    "some_count" int
);

CREATE VIEW "view_on_table" AS
SELECT some_text, some_date, some_count FROM my_table;

CREATE OR REPLACE FUNCTION my_function()
    RETURNS trigger
    LANGUAGE plpgsql
AS $function$
    BEGIN
        INSERT INTO my_table (some_text)
        VALUES (NEW.some_text);
        RETURN NEW;
    END;
$function$
;

CREATE TRIGGER trigger_on_view INSTEAD OF
INSERT ON view_on_table
FOR EACH ROW EXECUTE PROCEDURE my_function();
;
```

Migra output:
```SQL
drop view if exists "public"."view_on_table";

alter table "public"."my_table" add column "some_date" timestamp without time zone;

create or replace view "public"."view_on_table" as  SELECT my_table.some_text,
    my_table.some_date,
    my_table.some_count
   FROM my_table;
```

And although the trigger isn't explicitly dropped, you'll notice it's now missing from the `target` schema.

Running migra again gives it:
```SQL
CREATE TRIGGER trigger_on_view INSTEAD OF INSERT ON public.view_on_table FOR EACH ROW EXECUTE PROCEDURE my_function();
```

**Comment by djrobstep** [comment]
Thanks heaps for reporting this, the very comprehensive report and reproducible test case made it much easier to put together a fix.

Accordingly, it should be fixed as of the latest release.

**Comment by cyclotron3k** [comment]
Thanks man, really appreciate your work. I'd make a PR myself but I don't know python unfortunately.
