### ISSUE TITLE
Row level security not working

### ISSUE THREAD

**Issue by eleasarchriso** [djrobstep/migra#121]
Hi,

when I run migra it does not render the command to add row level security.

I have one DB where I created a single table:

```sql
CREATE TABLE example (
  id SERIAL PRIMARY KEY,
  name text NOT NULL
);
ALTER TABLE example ENABLE ROW LEVEL SECURITY;
CREATE POLICY example_all ON example FOR ALL
   USING (true);
```

And when I run this to compare against an empty DB table migra creates the following output:

command: `migra --with-privileges --unsafe postgres://postgres:postgres@localhost:5432/migra_shadow postgres://postgres:postgres@localhost:5432/migra_rls`

```sql
create sequence "public"."example_id_seq";

create table "public"."example" (
    "id" integer not null default nextval('example_id_seq'::regclass),
    "name" text not null
);


CREATE UNIQUE INDEX example_pkey ON public.example USING btree (id);

alter table "public"."example" add constraint "example_pkey" PRIMARY KEY using index "example_pkey";

create policy "example_all"
on "public"."example"
as permissive
for all
to unknown (OID=0)
using true;
```

Also not sure on the `to unknown (OID=0)` part.

I did run the latest install with `pip install migra[pg]` but not sure if I can really check if this one is the latest version. I did not see a "--version" option or similar.

**Comment by djrobstep** [comment]
Hmm, thanks heaps for reporting this. migra should be adding the command to do this. I will investigate

**Comment by djrobstep** [comment]
This should be fixed as of the latest release. The `unknown (OID=0)` bad output is also fixed now, `public` gets correctly output instead.
