### ISSUE TITLE
Default values having custom types are not handled when types are updated

### ISSUE THREAD

**Issue by gwn** [djrobstep/migra#124]
Say we have the following setup:

```
create type order_status as enum('pending', 'processing', 'complete');

create table orders(
  id serial primary key,
  status order_status default 'pending'::order_status
)
```

Let's add an 'rejected' status to it:

```
create type order_status as enum('pending', 'processing', 'complete', 'rejected');

create table orders(
  id serial primary key,
  status order_status default 'pending'::order_status
)
```

Here are the generated statements:

```
alter table "public"."orders" alter column "status" set data type varchar using "status"::varchar;

drop type "public"."order_status";

create type "public"."order_status" as enum ('pending', 'processing', 'complete', 'rejected');

alter table "public"."orders" alter column "status" set data type order_status using "status"::order_status;
```

The migration fails because dropping the `order_status` type is not permitted, as it is a dependency of the default value of the `status` field. Before dropping the `order_status` type, Migra also needs to add a statement to convert the default value of the `status` field to `text` as well, or cancel the default value altogether, only to take it back after the type is updated.

Here is the diff that should have been generated:

```
alter table "public"."orders" alter column "status" drop default;
alter table "public"."orders" alter column "status" set data type varchar using "status"::varchar;

drop type "public"."order_status";

create type "public"."order_status" as enum ('pending', 'processing', 'complete', 'rejected');

alter table "public"."orders" alter column "status" set data type order_status using "status"::order_status;
alter table "public"."orders" alter column "status" set default <previous default value>::"public"."order_status"
```

**Comment by djrobstep** [comment]
Good spotting. Looks like dropping the default entirely before making the change, is the way to go.

**Comment by gwn** [comment]
I will try to send a PR if I can find the time.

By the way, Migra is great and I thank you for it :)

**Comment by djrobstep** [comment]
This turned out to be a pretty easy fix so went ahead and added it, it should be in the latest release.

Really glad you enjoy migra, and thank you for the support (and sponsorship).

**Comment by gwn** [comment]
Thank you!!
