### ISSUE TITLE
Drop procedures with `drop procedure ...` not `drop function ...`

### ISSUE THREAD

**Issue by Dmitrii-I** [djrobstep/migra#127]
In my target database one stored procedure is not present anymore. Migra version 1.0.1588034927 generated `drop function ...` instead of `drop procedure ...` as the diff.

The `drop function ...` does not work for stored procedures (PostgreSQL 12).

**Comment by djrobstep** [comment]
Good spotting, thank you for reporting this. Pleased to say this is fixed as of the latest release.
