### ISSUE TITLE
[Feature request] Associate the sequence with the table

### ISSUE THREAD

**Issue by jgrocha** [djrobstep/migra#133]
Let's see how **migra** creates a table with `serial` on the origin.

### Original

```sql
CREATE TABLE line_product_type (
	id serial NOT NULL,
	designation varchar NOT NULL,
	CONSTRAINT line_product_type_pk PRIMARY KEY (id)
);
```

### Clone created by **migra**

```sql
create sequence "line_product_type_id_seq";
create table "line_product_type" (
    "id" integer not null default nextval('line_product_type_id_seq'::regclass),
    "designation" character varying not null
);
```

### The limitation

The sequence is created manually. It is not associated with the table. This way, `select pg_get_serial_sequence('line_product_type', 'id');` does not work.

### Workaround

Generate an additional DDL:

```sql
alter sequence line_product_type_id_seq owned by line_product_type.id;
```

**Comment by djrobstep** [comment]
This is fixed as of the latest release, let me know if you have any problems with it. Although I believe the recommendation these days is to use identities instead anyways!
