### ISSUE TITLE
Issues migrating sequences

### ISSUE THREAD

**Issue by gregplaysguitar** [djrobstep/migra#134]
Comparing the following dbs:

A.
```
create table test (
  id serial primary key
);
```

B.
```
create sequence "public"."test_id_seq";
create table "public"."test" (
    "id" integer not null default nextval('test_id_seq'::regclass)
);
CREATE UNIQUE INDEX test_pkey ON public.test USING btree (id);
alter table "public"."test" add constraint "test_pkey" PRIMARY KEY using index "test_pkey";
```

Migra now detects that the sequence ownership is different, but the output it gives is broken:

```
create sequence "public"."test_id_seq";
alter sequence "public"."test_id_seq" owned by "test"."id";
drop sequence if exists "public"."test_id_seq";
```

Note the order of statements, and the missing schema on `"test"."id"` in the second one.

---

As an aside, I tried to revert to the previous migra version, but the issue appears to be in schemainspect, and due to the open-ended dependency I kept getting the latest schemainspect version. I tried about 6 previous migra versions before I realised what was happening - I wonder if pinning the schemainspect version would be a good idea?

**Comment by gregplaysguitar** [comment]
(Just to be clear, there is no issue when the sequence ownership matches, so I didn't actually have to revert migra versions in the end, this issue only arises if there is a sequence ownership mismatch)

**Comment by djrobstep** [comment]
Good catch, this slipped through my tests. Rolling out a quick fix for this right now.

**Comment by djrobstep** [comment]
Should be fixed now.
