### ISSUE TITLE
Clarification on security - how to deal with passing the database password?

### ISSUE THREAD

**Issue by magicmark** [djrobstep/migra#138]
Hi! Thanks for this awesome project!

I'm a bit of a newcomer to the backend/databases world - looking for a clarification on the opinions this library has for handling the database password.

This quickstart guide and the docs suggest passing in the fully qualified path to the database via arguments to the CLI:

https://djrobstep.com/docs/migra/installing-and-connecting

1) Since this would show up in ps(1) and bash histories etc, is there a way around this? I was imagining something similar to the PGPASSFILE env variable where you could store this in a config file somewhere secure, so it doesn't show up in logs or whatever else a security team might be annoyed about

2) I  guess I could just consider the database password as not actually that sensitive - if an attacker has local access to the network where it would be of use, then there's far bigger problems...but principle of least privilege and all that...

3) Since I'd guess this would all be scripted in real world usage, maybe you're supposed to use the Python API where you might be able to avoid such issues? I wasn't able to see anything about this in the docs tho.

Thoughts?

Thanks so much!

**Comment by djrobstep** [comment]
Glad you're enjoying using `migra`. 

With the disclaimer that I'm no security specialist: The workarounds for passwords are much as you suggest - The most basic way to avoid passwords appearing in logs just to run the command within a bash or python script and embed your connection string in there, or grab it from a config file.

I don't use one myself but looks like you can also use a `.pgpass` file: https://www.postgresql.org/docs/12/libpq-pgpass.html

There's also various other forms of authentication you can set up: https://www.postgresql.org/docs/12/auth-methods.html

**Comment by magicmark** [comment]
Ah thanks! I didn't realize migra supported `.pgpass`, I'll try that :) (and maybe send a PR to clarify in the docs)

> run the command within a bash or python script and embed your connection string in there

Just a quick note to elaborate on the security implications here - here's a quick repro of the concerns:

```
$ cat test.py
import subprocess
subprocess.run(('bash', '-c', 'sleep 4 && echo "yikes you can see these args via ps(1)!"'));

$ python test.py &   
[1] 88911

$  ps aux | grep yikes
mark             88936   0.0  0.0  4399928   1084 s005  SN    4:57PM   0:00.00 bash -c sleep 4 && echo "yikes you can see these args via ps(1)!"
```

thanks agin!

**Comment by djrobstep** [comment]
I have not confirmed that .pgpass works with migra, but migra uses sqlalchemy under the hood (which itself uses libpq under the hood) - so it supports whatever sqlalchemy supports.

Should add that within a script you would want to set the connection strings as variables - not embed them directly into the command.
