### ISSUE TITLE
Tagged releases

### ISSUE THREAD

**Issue by cep21** [djrobstep/migra#139]
Hi,

Thanks for this project!  Does Migra follow semantic versioning?  For stability reasons, I would like to lock down the version of migra I use.  There is a docker image for Migra here https://hub.docker.com/r/djrobstep/migra/dockerfile but it looks like everything is built as `latest`.  Is it possible to have release versions (1.0, 1.1, etc)?

Thanks!

**Comment by djrobstep** [comment]
Versioning at the moment is pretty simple, I take a continuous integration approach where a new release is made to PyPI every time a commit hits master. The patch version is simply the unix timestamp that version was made.

You can install all of these versions individually via PyPI but we don't currently do Docker tagging, I will set this up.

I don't tend to change the major/minor versions much, as migra's external interface doesn't change much, and most new versions are just bugfixes or newly supported features. 

I will however be incrementing the major version to 3 as soon as I stop supporting Python 2 (which will be soon), and probably each time I drop support for a major postgres version.

I'd be interested to know if you you are wanting a particular version simply for version pinning or if you're encountering bugs in newer versions that weren't present in old versions.

**Comment by cep21** [comment]
> simply for version pinning or if you're encountering bugs in newer versions that weren't present in old versions

Just for pinning versions.  My primary goal is to create a reliable build/deployment pipeline that uses migra.  With tagged releases that follow SEMVER, I can keep my builds consistent over time, be aware of any important changes and try them in a staging environment first, and give you the flexibility to change obscure behavior in backwards incompatible ways while being aware of any such possible changes.

**Comment by djrobstep** [comment]
This is in place now for the current and all future releases!
