### ISSUE TITLE
Problem with line breaks when diffing and generating SQL

### ISSUE THREAD

**Issue by PedroSolintel** [djrobstep/migra#15]
Let's say I have a function in DB2:

```
create or replace function "public"."test_function"()
returns void AS
$$
DECLARE
	testvar TEXT;
BEGIN
	SELECT testvar;

	SELECT testvar || '2';
END;$$
language PLPGSQL VOLATILE CALLED ON NULL INPUT SECURITY INVOKER;
```

Then, when I use migra to update DB1 to DB2, migra generates the following SQL:

```
create or replace function "public"."test_function"()
returns void as
$$

DECLARE

	testvar TEXT;

BEGIN

	SELECT testvar;



	SELECT testvar || '2';

END;$$
language PLPGSQL VOLATILE CALLED ON NULL INPUT SECURITY INVOKER;
```

If I run migra again, it will still find a difference and migra will generate the same script as above. However, if I decide to run migra inverting the sides and updating DB2 to DB1:

```
create or replace function "public"."test_function"()
returns void as
$$



DECLARE



	testvar TEXT;



BEGIN



	SELECT testvar;







	SELECT testvar || '2';



END;$$
language PLPGSQL VOLATILE CALLED ON NULL INPUT SECURITY INVOKER;
```

It keeps duplicating line breaks.

**Comment by djrobstep** [comment]
Could you give me more details on your setup and how you're running migra? I can't replicate this on any of my setups.

**Comment by djrobstep** [comment]
closing for lack of reproducibility
