### ISSUE TITLE
Comparing 2 database.  

### ISSUE THREAD

**Issue by josieguidewire** [djrobstep/migra#151]
Hi,

I have 2 databases.  They should be exactly a like.  Database b was a pgdump from database A.  I was expecting migra to not have any differences, but it did.  Differences were mostly functions and indexes.  When i went to validate, they were actually there in the database.  

How is that possible?  How does migra do the comparison? 

THanks!

**Comment by djrobstep** [comment]
Migra does the comparison by directly inspecting the two databases.

I can't diagnose your issue further without a reproducible example - if you can provide an a.sql and b.sql that when loaded and compared don't show the correct differences, I can investigate.

**Comment by josieguidewire** [comment]
Here is what I did.  I have database a.  I did a pg_dump of the database.  I used the dump to create database b.  I did a compare from a to b and then b to a.   Both had differences but the difference were really not different they were present in the corresponding database.  It was mostly pk, index and functions.  Everything else matched.  I am not sure i can send it to you but i can ask.  You could try what i did and see if you get the same results.  Let me see if i can send you sql.  
Thanks!

**Comment by djrobstep** [comment]
Unless there's a massive bug I'm not aware of that is slipping through our tests, that shouldn't be happening.

PKs, indexes, and functions are all tracked. Are you sure there's nothing different about them? 

Please supply example schemas if you can, otherwise I have no way to narrow down the problem.
