### ISSUE TITLE
Compare 2 remote databases

### ISSUE THREAD

**Issue by agjs** [djrobstep/migra#153]
Hi there and thanks for all the work you are putting in. I'm currently setting up the entire infra for my team and I'd like to try and use migra in diffing the databases. But before I attempt to do such thing, I'd love to ask a question and see if it can accommodate our use case. 

I'd love to compare a database from a container ran by my Jenkins with a remote database running on a different server and get a diff output in the shared volume between jenkins and the docker container. Is is possible with migra to actually connect to a remote database, aka provide some sort of SSH tunnel URL e.g.

```
migra postgresql:///a ssh -L 63333:localhost:5432 joe@foo.com
```
as described [here](https://www.postgresql.org/docs/9.1/ssh-tunnels.html)

If this is not possible, would you have any suggestions of how would this work? 

Kind regards,
Alexander

**Comment by djrobstep** [comment]
There's no built-in functionality for setting up tunnels, so you need to set them up separately.

A couple of options:

- Run a tunnel command separately. Once connected, run migra, pointing it at the local end of the tunnel.
- Use migra within a python script, and use paramiko to create tunnel on demand. This would be the rough pseudocode:

```
with paramiko_tunnel() as t:
    m = Migration(db_a, db_b)
    ...
```

**Comment by agjs** [comment]
> There's no built-in functionality for setting up tunnels, so you need to set them up separately.
> 
> A couple of options:
> 
> * Run a tunnel command separately. Once connected, run migra, pointing it at the local end of the tunnel.
> * Use migra within a python script, and use paramiko to create tunnel on demand. This would be the rough pseudocode:
> 
> ```
> with paramiko_tunnel() as t:
>     m = Migration(db_a, db_b)
>     ...
> ```

Thanks a lot @djrobstep. Will give it a shot today. Appreciate the help!

Alex
