### ISSUE TITLE
Change in order of index columns: not treated as different

### ISSUE THREAD

**Issue by hi2u** [djrobstep/migra#154]
See the two example schemas below.  Note that for the indexes:

* in v1, the order of the index columns is: col_a, col_b
* in v2, the order has been changed: col_b, col_a

...but migra doesn't see this as being any different, and therefore doesn't produce any diff commands.  They should be treated as different, as the order of columns is significant in indexes.

I could be wrong, but I thought that this was working for some (but maybe not all) of my indexes the order changed in the past.  But it doesn't seem to work for all my indexes right now, including this example I've created below.  So not entirely sure if it does actually work in certain situations sometimes / maybe is a regression.  Or whether it's not actually implemented yet?

I'm running the latest versions of migra + schemainspect installed via pip3:

```
pip3 list --format=columns | grep -iE "migra|psycopg|schemainspect"
migra               1.0.1602274611
psycopg2            2.8.5
psycopg2-binary     2.8.6
schemainspect       0.1.1602274168
```

# blueprint v1

```postgresql
CREATE TABLE test_nobackup.demo_swapping_table (
	id uuid NOT NULL,
	col_a int4 NULL,
	col_b int4 NULL,
	CONSTRAINT demo_swapping_table_pkey PRIMARY KEY (id)
);
CREATE UNIQUE INDEX dcode_index_652172e37c35458fa6f74814fa3f34ea ON test_nobackup.demo_swapping_table USING btree (col_a, col_b);
```

# blueprint v2

```postgresql
CREATE TABLE test_nobackup.demo_swapping_table (
	id uuid NOT NULL,
	col_a int4 NULL,
	col_b int4 NULL,
	CONSTRAINT demo_swapping_table_pkey PRIMARY KEY (id)
);
CREATE UNIQUE INDEX dcode_index_652172e37c35458fa6f74814fa3f34ea ON test_nobackup.demo_swapping_table USING btree (col_b, col_a);
```

**Comment by djrobstep** [comment]
Good catch - I also thought this did work before. In any case, it's now fixed as of the latest release. Let me know if you have any further problems.

**Comment by hi2u** [comment]
Awesome, thanks so much!
