### ISSUE TITLE
Views can depend on primary keys

### ISSUE THREAD

**Issue by trendels** [djrobstep/migra#156]
I tested migra against some large db schemas recently, and ran into this interesting issue:

The view in this example does a `group by` on a primary key column. In Postgres this allows you to omit other columns of the same table from the `group by`. This also means that the view now depends on the primary key:

```
create table t (
    id integer not null primary key,
    a text,
    b integer
);

create view v as
select id, a, max(b)
from t
group by id;  -- "a" is implied because "id" is primary key
```

When comparing against an empty database, migra generates this SQL:

```
create table "public"."t" (
    "id" integer not null,
    "a" text,
    "b" integer
);


create or replace view "public"."v" as  SELECT t.id,
    t.a,
    max(t.b) AS max
   FROM t
  GROUP BY t.id;


CREATE UNIQUE INDEX t_pkey ON public.t USING btree (id);

alter table "public"."t" add constraint "t_pkey" PRIMARY KEY using index "t_pkey";
```

Applying this migration fails, because the the view definition comes before the primary key:

```
psql:migra.sql:12: ERROR:  column "t.a" must appear in the GROUP BY clause or be used in an aggregate function
LINE 2:     t.a,
            ^
```

`pg_dump` handles the dependency this way: The view is defined as a "dummy" first, which is replaced by the real implementation after the primary key has been added:

```
-- relevant lines of `pg_dump --schema-only` output

CREATE TABLE public.t (
    id integer NOT NULL,
    a text,
    b integer
);

CREATE VIEW public.v AS
SELECT
    NULL::integer AS id,
    NULL::text AS a,
    NULL::integer AS max;

ALTER TABLE ONLY public.t
    ADD CONSTRAINT t_pkey PRIMARY KEY (id);

CREATE OR REPLACE VIEW public.v AS
 SELECT t.id,
    t.a,
    max(t.b) AS max
   FROM public.t
  GROUP BY t.id;
```

As far as I can see migra/schemainspect do not currently track these kinds of dependencies.

**Comment by trendels** [comment]
In the system tables, the dependency is recorded between the constraint (in `pg_constraint`) and the view's entry in `pg_rewrite`:

```
a=# select oid, conname from pg_constraint where conname = 't_pkey';                               
  oid   | conname 
--------+---------
 509170 | t_pkey
(1 row)

a=# select r.oid, c.relname                                                                        
from pg_rewrite r
    join pg_class c on r.ev_class = c.oid
where c.relname = 'v';
  oid   | relname 
--------+---------
 509174 | v
(1 row)

a=# select classid::regclass, objid, objsubid, refclassid::regclass, refobjid, refobjsubid, deptype
from pg_depend
where objid = 509174 and refobjid = 509170;
  classid   | objid  | objsubid |  refclassid   | refobjid | refobjsubid | deptype 
------------+--------+----------+---------------+----------+-------------+---------
 pg_rewrite | 509174 |        0 | pg_constraint |   509170 |           0 | n
(1 row)
```

**Comment by djrobstep** [comment]
Interesting - thanks for reporting this. I hadn't considered this dependency thus far. This can possibly be solved straightforwardly by moving view creation after primary key creation in the process.

Will try that approach and see how well it works or if it breaks anything else.

**Comment by trendels** [comment]
That was my first thought as well, but it might not work if there are more complex dependencies. For example a materialized view could be added on top of that view, and then an index on the materialized view ...

**Comment by djrobstep** [comment]
I've had a go at fixing this, try the latest release and see how it works for you.

Statements should now be emitted in this order:

- Table additions and changes
- Indexes/constraints creations
- View creations/replacements

**Comment by trendels** [comment]
Sorry, I haven't had time to test this until today. Changing the statement order did fix the original issue, but it introduces another one: Indexes on materialized view are now created before the view they reference:
```
create table t (id integer);
create materialized view mv as select * from t;
create index on mv (id);
```

migra output:
```
create table "public"."t" (
    "id" integer
);


CREATE INDEX mv_id_idx ON public.mv USING btree (id);

create materialized view "public"."mv" as  SELECT t.id
   FROM t;
```

**Comment by djrobstep** [comment]
OK I've now fixed this by changing the ordering to:

```
- Matview index drops
- View/function/matview drops
- Non-matview index drops
- Table changes
- Non-matview index creations
- View/function/matview creations
- Matview index creations
```

Can you think of any further scenarios that this ordering won't handle?

**Comment by trendels** [comment]
This works perfeclty :+1:
