### ISSUE TITLE
No point of no changes

### ISSUE THREAD

**Issue by noveb** [djrobstep/migra#157]
Hello,

thanks for this nice pice of software! I am evaluating the use in our company and run in a problem:

If I diff DB A versus a copy of A in DB B (actually a dump without owners and privileges) the result shows a lot (or maybe all) triggers and related functions. There are first drops of triggers and functions and then create commands for them.
I then applied the changes and run the diff again. I expected to get no or less changes in the second diff but there are almost exactly the same changes found. I can repeat this over and over.

Any suggestions why this would happen and how to fix this?

Kind regards

**Comment by djrobstep** [comment]
Hi, thanks for filing this issue. That shouldn't be happening.

Can you give me a reproducible example schema that this happens for?

**Comment by daniel-webber** [comment]
I recently experienced this same issue between two DBs. I discovered the reason was that the function in DB-B (source) was owned by a role that did not exist in DB-A (target). This was without the --with-privileges flag if that helps.

**Comment by djrobstep** [comment]
Closing this old issue as part of some routine cleanup :) Feel free to reopen if still relevant.
