### ISSUE TITLE
Is there a way to print the sql that is generated as part of a migra run?

### ISSUE THREAD

**Issue by tzaffi** [djrobstep/migra#163]
Hi Robert,

I really love migra and gotta say that your pycon presentation on it is one of my all time favorites, and definitely my favorite title! 

I believe my `migra` execution is blowing up because of a permissioning issue but it's hard to tell because I don't know how to get the raw SQL out that `migra` has executed. I know that -in theory- sqlalchemy can print out the SQL that it ran if you supply engine with an `echo=True` parameter (https://docs.sqlalchemy.org/en/13/core/engines.html?highlight=echo#sqlalchemy.create_engine.params.echo). I tried playing around with the **dburl**, adding `?echo=True` and `?echo=true` as a suffix, but that didn't work. 

Is there a way to expose the SQL?  

If not, you can view view this issue as a "feature request" instead.  And if you're too busy on that front, and you think it's a useful feature, I could aim to make a PR in that direction.

In any case, here's the stack-trace that I got. The same `migra` run worked just fine on databases that I had full priveleges on.

```bash
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/ds-scikit-38/bin/migra", line 8, in <module>
    sys.exit(do_command())
  File "/usr/local/Caskroom/miniconda/base/envs/ds-scikit-38/lib/python3.8/site-packages/migra/command.py", line 108, in do_command
    status = run(args)
  File "/usr/local/Caskroom/miniconda/base/envs/ds-scikit-38/lib/python3.8/site-packages/migra/command.py", line 79, in run
    m = Migration(ac0, ac1, schema=schema, exclude_schema=exclude_schema)
  File "/usr/local/Caskroom/miniconda/base/envs/ds-scikit-38/lib/python3.8/site-packages/migra/migra.py", line 33, in __init__
    self.changes.i_target = get_inspector(
  File "/usr/local/Caskroom/miniconda/base/envs/ds-scikit-38/lib/python3.8/site-packages/schemainspect/get.py", line 20, in get_inspector
    inspected = ic(c)
  File "/usr/local/Caskroom/miniconda/base/envs/ds-scikit-38/lib/python3.8/site-packages/schemainspect/pg/obj.py", line 1060, in __init__
    super(PostgreSQL, self).__init__(c, include_internal)
  File "/usr/local/Caskroom/miniconda/base/envs/ds-scikit-38/lib/python3.8/site-packages/schemainspect/inspector.py", line 25, in __init__
    self.load_all()
  File "/usr/local/Caskroom/miniconda/base/envs/ds-scikit-38/lib/python3.8/site-packages/schemainspect/pg/obj.py", line 1064, in load_all
    self.load_all_relations()
  File "/usr/local/Caskroom/miniconda/base/envs/ds-scikit-38/lib/python3.8/site-packages/schemainspect/pg/obj.py", line 1437, in load_all_relations
    self.relations[t].indexes[n] = each
KeyError: '"public"."auth_group_permissions"'
```

**Comment by tzaffi** [comment]
I should probably also provide the command that I ran:
```bash
migra --schema=SOME_SCHEMA --unsafe postgresql://...SOME DB INFO... postgresql://...SOME OTHER DB INFO...
```

I also tried adding the `--with-privileges` flag but got the same output.

**Comment by djrobstep** [comment]
Hey, thanks for filing this. I'm glad you enjoy migra and like the philosophy behind it.

You should be able to get the queries themselves `echo`ing with code similar to the following:

```
from sqlbag import S
from schemainspect import get_inspector

with S('postgresql:///example', echo=True) as s:
    i = get_inspector(s)
```

Let me know if that does the trick (it just passes that parameter along to sqlalchemy under the hood, so I'm not sure why using `echo` isn't already working for you).

As you have discovered, the code is currently quite brittle in this situation and similar situations when it cannot fully read the database and the information it expects to be there is missing. It could definitely be improved.

**Comment by tzaffi** [comment]
Yeah, that worked thanks! Turns out, it was completely a red herring. The reason it's blowing up is that the DB is in bad shape. There is an index defined on a no longer exiting table, so the index is being attempted to be added to a non-existant key in `self.relations`.

I'm not sure what can be done about that. Maybe add some sentinel relation "DATABASE_DESIGN_ERRORS" or something like that, but that's not an elegant solution. In this case, it belongs to a schema that I'm not interested in, so maybe there's a way to limit the inspector only to one schema when the `--schema` argument is included.

Oh well.

**Comment by tzaffi** [comment]
You can go ahead and close this issue, unless you find some value in keeping it alive.

**Comment by tzaffi** [comment]
Oh yeah, I should say it's still a mystery to me why explicitly adding `echo=True` in the `SQLbag` works while `?echo=True` in the URL doesn't.

**Comment by tzaffi** [comment]
Actually, I take it back. That table actually does exist, but somehow it's not being picked up. I'll have to dig a little deeper.

**Comment by tzaffi** [comment]
I identified the issue. This [line of code](https://github.com/djrobstep/schemainspect/blob/7c2cb34776fbc8da1783dc306b411b892b3fcfd9/schemainspect/pg/sql/relations9.sql#L51) which is now commented out was causing the table to be missing from the list of relations.

Given that this has been commented out for more than a year, it looks like I need to upgrade to the latest version of `schemainspect`. I'm guessing `migras` dependencies need to be updated as well.

**Comment by djrobstep** [comment]
That line of code will in fact be included in the query uncommented. The queries go through a layer of text processing before  actually run against the database.

**Comment by tzaffi** [comment]
I see, well that line which is specifying that `e.objid is null` in the CTE is what's breaking my migra run, since I do in fact have tables with non-null obj.id's. I'm not a database expert so don't know if that's unexpected or not.

**Comment by djrobstep** [comment]
Closing this old issue as part of some routine cleanup :)
