### ISSUE TITLE
Function names must be less than 64 characters

### ISSUE THREAD

**Issue by stephensamra** [djrobstep/migra#167]
`migra` throws an error when it encounters a function with a name that is 64 characters or greater.

For example, creating the following function in a database and then running `migra` against it will throw an error.
```sql
CREATE OR REPLACE FUNCTION public.xxxxxx_this_function_is_sixty_four_characters_long_xxxxxx ()
    RETURNS INTEGER AS $sample_number$
        DECLARE sample_number INTEGER;
    BEGIN
    SELECT 64 INTO sample_number;
    RETURN sample_number;
END;
$sample_number$ LANGUAGE plpgsql;
```

The 64 characters includes `public.`.

If I remove a single character from the function name then `migra` runs without error.

The error thrown is:
```
Traceback (most recent call last):
  File "/usr/bin/migra", line 8, in <module>
    sys.exit(do_command())
  File "/usr/lib/python3.6/site-packages/migra/command.py", line 108, in do_command
    status = run(args)
  File "/usr/lib/python3.6/site-packages/migra/command.py", line 85, in run
    m.add_all_changes(privileges=args.with_privileges)
  File "/usr/lib/python3.6/site-packages/migra/migra.py", line 106, in add_all_changes
    self.add(self.changes.non_table_selectable_creations())
  File "/usr/lib/python3.6/site-packages/migra/changes.py", line 498, in get_selectable_changes
    old=selectables_from,
  File "/usr/lib/python3.6/site-packages/migra/changes.py", line 125, in statements_from_differences
    statements.append(v.create_statement)
  File "/usr/lib/python3.6/site-packages/schemainspect/pg/obj.py", line 290, in create_statement
    return self.full_definition + ";"
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

Is this a limitation of `migra` or a bug? If it is a limitation, I think it should be documented somewhere as a known issue.

Thanks for reading.

**Comment by djrobstep** [comment]
Postgres has a hard limit of 63 bytes for identifiers, however what you encountered here was a bug in the function inspection query that broke the query with names > 56 characters.

(Note that the 63 limit is per identifier so doesn't include the schema name)

Anyway, this has now been fixed as of the latest `schemainspect` release, so function names right up to the 63 char limit should now work fine. Let me know if you run into any further issues with this.

**Comment by stephensamra** [comment]
@djrobstep thanks for the info and the fix. I'll try it out later today and let you know if I run into any issues.
