### ISSUE TITLE
Ability to ignore a regex of table names or ignore temp tables by default

### ISSUE THREAD

**Issue by jmntn2000** [djrobstep/migra#17]
When running the temp tables are always showing up.  If you had ability to limit comparison to a schema, skip tables names by regex such as pg_temp_* or just by default skip the pg temp tables that would make the output much cleaner.

**Comment by djrobstep** [comment]
Hey, thanks for reporting this issue, and sorry for the slow response! 

Those tables shouldn't be showing up.. can you give me an example scenario where that happens so I can reproduce?

**Comment by djrobstep** [comment]
Cannot reproduce so closing for now
