### ISSUE TITLE
Generating one file for each script

### ISSUE THREAD

**Issue by aruna7187** [djrobstep/migra#183]
I liked the framework. but i have a specific request that i like to achieve using migra db compare.
i want to generate separate files for each script(may be we can have table/view/function..etc folder structures or in a single folder) . This will make easy to review or maintain the changes and if we want to store script changes somewhere (GitHub or another platform).

**Comment by maximsmol** [comment]
The main issue with separating one migration across multiple files is that some objects have dependencies between them. For example, if a table has a column with an `enum` type then that enum must exist before the table can be created. This would require running the `enum` migrations file before the table migrations file.

Moreover, there could be dependency chains that make it so the migration cannot be partitioned into multiple files at all. For example, a table might use a function in a column's `default` but that function might use another table's row type as its output. This would create the following dependency graph: `table1 -> default_generator -> table2` and neither the table migrations file nor the function migrations file could be run on their own. Here is the schema for this example:
```plpgsql
create table table1(
  id bigint not null
);

create function default_generator()
returns table1.id%type
as ... volatile;

create table table2(
  table1_reference bigint default default_generator()
);
```

So we could break the migration into files sometimes but not in the general case. This might still be useful but I'd like to design this based on some actual use-cases/workflows. If somebody is still interested in this, feel free to comment with an example use case and I'll reopen, but I'm closing for now as there does not seem to be a clear direction forward.
