### ISSUE TITLE
CREATE SCHEMA commands aren't migrated

### ISSUE THREAD

**Issue by iMHLv2** [djrobstep/migra#20]
If you add the following to your source database:

```
create schema myschema;
create table myschema.new_table (myint1 int);
```

Migra outputs the following:

```
create table "myschema"."new_table" (
    "myint1" integer
);
```

However that will fail to be applied to the destination database, because the `myschema` schema won't exist (unless edited manually of course).

**Comment by djrobstep** [comment]
Thanks for reporting this issue! 

Indeed these statements don't currently get output as they should. 

It's on my list of things to fix, but not sure how quickly that will happen as I'm fairly busy these days.

Or if you fancied fixing it yourself I can talk you through what would be needed?

**Comment by djrobstep** [comment]
This should be fixed now, try it out and let me know how it goes for you.
