### ISSUE TITLE
Exclude constraint gets incorrectly created when multiple operations are present.

### ISSUE THREAD

**Issue by AidanAbd** [djrobstep/migra#205]
Steps to reproduce:
* Add a constraint of the form `exclude using gist (column_1 with =, column_2 with =);`

Diff behavior to create constraint
* `CREATE INDEX pod_session_pod_id_coalesce_excl ON app_public.pod_session USING gist (column_1, column_2);`

Expected Behavior
* `alter table app_public.pod_session add constraint pod_session_pod_id_coalesce_excl exclude using gist (column_1 with =, column_2 with =);`

**Comment by kevinmehall** [comment]
Same as https://github.com/djrobstep/migra/issues/147

**Comment by djrobstep** [comment]
Closing as duplicate.
