### ISSUE TITLE
insert statements not generated

### ISSUE THREAD

**Issue by Asta1986** [djrobstep/migra#21]
Hello, first of all let me say thank you I think migra is a great project.
I've tried to compare two databases with the same columns in a table but one with no rows and the other one with a few ones and I didn't see any insert statements in the output of migra.
Is this the expected behavior or should differences in rows also be taken into account?
Regards.

**Comment by djrobstep** [comment]
Hi there, thank you for filing this issue! I'm really glad you like the project, it's encouraging to hear feedback like that.

Currently `migra` supports only comparison of schemas, and don't consider the contents of tables at all.

It would be cool if migra could also handle row contents and diff those too, and I'd like to add such functionality in the future.

I'm unlikely to have the chance to implement this myself in the near future, but pull requests would always be welcome :)

**Comment by djrobstep** [comment]
Closing this, plans for content diffing in the future are addressed in https://github.com/djrobstep/migra/issues/24
