### ISSUE TITLE
The --schema flag seems to be ignored for rls policies

### ISSUE THREAD

**Issue by aron-kunze** [djrobstep/migra#211]
When running migra with --schema $schema, rls policies are created for tables that are in other schemas. 

From a quick glance at the code it seems the problem is caused by a missing entry here in (schemainspect/pg/obj.py): 

```python
PROPS = "schemas relations tables views functions selectables sequences constraints indexes enums extensions privileges collations triggers"
```

**Comment by djrobstep** [comment]
Should be fixed now, as of the latest `schemainspect` release.
