### ISSUE TITLE
Rename primary key instead drop and create

### ISSUE THREAD

**Issue by jozef-slezak** [djrobstep/migra#213]
AS-IS: when we rename the primary key then drop & create statements are generated

expected behavior: rename the primary key / index / constraint if the type has not been changed

**Comment by djrobstep** [comment]
Thanks for filing this - I'm not sure if it's possible to fix this, however - it's not watertight to make assumptions about renaming based on the state of the constraints: Fundamentally it's impossible to tell the difference between a new and renamed column when only looking at the schema.

Adding configurability for renaming however is a possible future addition. In the short term, I'll create ticket for this.
