### ISSUE TITLE
empty tables are ignored by migra

### ISSUE THREAD

**Issue by Asta1986** [djrobstep/migra#22]
Hello, I've noticed when I create an empty table (no columns nor rows) in one database migra does not output a create table statement for it (for instance
`CREATE TABLE table_name ();`)
although the object exists in the "from" database.
Best regards.

**Comment by djrobstep** [comment]
Well spotted! I wasn't aware that tables with no columns could be created. Fixing this will require modification of the [schemainspect](https://github.com/djrobstep/schemainspect) project that does the actual querying of schema structure, in order for it to accurately report these tables.

I'll add this as an issue over there.

**Comment by djrobstep** [comment]
Finally fixed this one!
