### ISSUE TITLE
documentation down

### ISSUE THREAD

**Issue by willm** [djrobstep/migra#225]
Hi,

I'm just wondering if there's somewhere we can access the documentation even in code form while the site is down for maintenance?

Thanks

**Comment by nelsonic** [comment]
2023-01-29 04:20 GMT Site is still:

# "Down for maintenance. Back soon!"

![image](https://user-images.githubusercontent.com/194400/215306063-417382df-7c0e-411a-87be-4ea94d3ef06e.png)

Reading docs on `GitHub` in the mean time: https://github.com/djrobstep/migra/blob/master/docs/quickstart.md 👀 

This project looks _really_ promising. 😍 
Hoping to recommend it to our team ⭐ 
but don't want the _first_ thing they see when they click to view the project website: 🔗 

<img width="1167" alt="migra-github-repo-link-down" src="https://user-images.githubusercontent.com/194400/215306276-1b78834f-e36b-44af-9115-0703e9c0ae0b.png">

To be "Down for maintenance" ... ⏳ 
is there anything people in the _community_ can do to get the docs site back online? 👨‍💻 
Or could the link be updated to point to a GitHub Pages site that _always_ works? 💭 

## Further Context 

Discovered your project while trying to figure out how to do schema migrations for `Supabase`: 🦸 
https://www.slip.so/tutorials/database-migrations-in-supabase-with-migra

**Comment by djrobstep** [comment]
Back up now.
