### ISSUE TITLE
Phase out Python 2

### ISSUE THREAD

**Issue by djrobstep** [djrobstep/migra#26]
Thinking of phasing out v2 for code cleanliness.

More compelling once v3.7 comes out: No more unordered dicts, and can use the new data classes (they'll be especially useful in https://github.com/djrobstep/schemainspect).

Would rather focus any dev time on better features rather than backward compatibility.

**Comment by eradman** [comment]
Cent7.4 only ships with Python 2.7.5 Personally I could work around this, but at the moment Python 2 compability is helpful.

**Comment by djrobstep** [comment]
Understandable, thanks for letting me know. Will try to maintain the the py2 compatibility at least until we hit a real pain point.

**Comment by djrobstep** [comment]
Python 2 reaches end-of-life at the end of this month - that seems like a good time to stop supporting it. We'll do a final 2-compatible release in early Jan and then support only >=3.6 after that.

**Comment by maximsmol** [comment]
Seems like Python 2 is not supported based on the `pyproject.toml`—can we close this? @djrobstep

**Comment by djrobstep** [comment]
Yep py2 has not been supported for some time. Closing.
