### ISSUE TITLE
Migra Does not Handle Types

### ISSUE THREAD

**Issue by qpfiffer** [djrobstep/migra#31]
Adding support for new/different data types would be very useful.

**Comment by djrobstep** [comment]
Sure would! 

I will try and work on this when I have time, but it won't be soon, unfortunately.

If you need it soon, I'd be delighted to receive pull requests.

**Comment by savv** [comment]
@djrobstep  I noticed that this commit:

https://github.com/djrobstep/migra/commit/7f6f91e2df1c216f6fbb02f6aa2f22adedc58c03

adds better handling for enums. Specifically, it seems to rename the current enum, and change all tables that use it. Unfortunately, it doesn't seem to work if views are using that type [1].

Would it make sense to add/remove individual elements if the name/schema hasn't changed?
Would it make sense to ignore differences in enum order?

Happy to send a PR that handles these two cases in `get_enum_modifications`. Let me know!


[1]
psql:migra.sql:*****: ERROR:  cannot alter type of a column used by a view or rule
DETAIL:  rule _RETURN on view ********* depends on column *******

**Comment by djrobstep** [comment]
The trouble with adding/removing individual elements is that not all operations are supported. For instance, you can insert new values but cannot reorder existing values. There are also performance issues with modifying existing enum values (I have not encountered them but they are [noted in the docs](https://www.postgresql.org/docs/12/sql-altertype.html), under "Notes"). For versions before 12, there's also the issue that the "ALTER TYPE ... ADD VALUE (the form that adds a new value to an enum type) cannot be executed inside a transaction block" - migra output is designed to be runnable within a transaction.

Ignoring differences is enum order is also not possible as ordering is very significant to enums, they are often used for greater than/less than comparisons, order by, etc etc.

AFAICT the most watertight way to solve the problem you're experiencing is to track enum dependencies, and drop/recreate the necessary views before modifying the enums. Currently we do track view dependencies, but enums aren't handled.

I have some preliminary work underway to fix this up, which I hope to publish soon.

**Comment by djrobstep** [comment]
Update: I've actually pushed a fix for this now. Views will now be dropped/recreated appropriately to allow enum changes.
