### ISSUE TITLE
Issue comparing schema changes with pg_dump 9.6.8

### ISSUE THREAD

**Issue by matt-sm** [djrobstep/migra#35]
`pg_dump` slightly changed the output in 9.6.8 due to a `search_path` vulnerability:

https://www.postgresql.org/docs/9.6/static/release-9-6-8.html

What this means is that this line no longer appears in `pg_dump` output:
- `SET search_path = public, pg_catalog;`

It is replaced by:
- `SELECT pg_catalog.set_config('search_path', '', false);`
- all tables prefixed with `public.`

I think this affects `migra` comparisons, particularly comparing alchemy models and a schema imported from `pg_dump`.  The database is loaded correctly but the `add_all_changes()` says that the entire model does not match the database.  

I have been able to work around this by removing the `SELECT pg_catalog.set_config()` line from the `pg_dump` output, but am still trying to figure out why the `migra` comparison is failing.

**Comment by djrobstep** [comment]
Are you by any chance loading the dump and running the comparison in the same session?

My understanding is that setting search paths only lasts for the duration of the session.

Best to load the dump, finish the session, then do the comparison in its own session.

However, even within the same session, the comparisons shouldn't fail. Could you provide a minimal example of a schema dump that causes problems? Can just be a single table or whatever. That should help me investigate. I wonder if this issue affects v10 also?

**Comment by matt-sm** [comment]
Rob,

I upgraded to the latest version of Migra and it still has the same issue

Here is a link to the code that runs the migration:

https://github.com/AusDTO/dto-digitalmarketplace-api/blob/master/migrations.py#L110

You can see the schema and the model are loaded into temp dbs, then the comparison happens in a session.

A minimal example that fails:
```
--
-- PostgreSQL database dump
--

-- Dumped from database version 9.6.6
-- Dumped by pg_dump version 9.6.9

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: plpgsql; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;


--
-- Name: EXTENSION plpgsql; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';


--
-- Name: pg_trgm; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;


--
-- Name: EXTENSION pg_trgm; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pg_trgm IS 'text similarity measurement and index searching based on trigrams';

--
-- Name: contact; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contact (
    id integer NOT NULL,
    contact_for character varying,
    name character varying NOT NULL,
    role character varying,
    email character varying,
    phone character varying,
    fax character varying
);


--
-- Name: contact_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.contact_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: contact_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.contact_id_seq OWNED BY public.contact.id;
```
This is the corresponding model:
```
class Contact(db.Model):
    __tablename__ = 'contact'
    id = db.Column(db.Integer, primary_key=True)
    contact_for = db.Column(db.String, index=False, nullable=True)
    name = db.Column(db.String, index=False, nullable=False)
    role = db.Column(db.String, index=False, nullable=True)
    email = db.Column(db.String, index=False, nullable=True)
    phone = db.Column(db.String, index=False, nullable=True)
    fax = db.Column(db.String, index=False, nullable=True)

```

**Comment by djrobstep** [comment]
Sorry for the slow reply on this, been away.

Looked into it and it turns out that because of connection pooling, the search path gets (wrongly) retained by sqlalchemy between sessions.

You can prevent the search path changes from leaking between sessions by disabling connection pooling on session that make search path changes:

```
from sqlbag import S
from sqlalchemy.pool import NullPool

with S(DB, poolclass=NullPool) as s:
    ...
```

**Comment by matt-sm** [comment]
Ah great.  Thanks for looking into this Rob!
