### ISSUE TITLE
Alpine Docker image (not an issue)

### ISSUE THREAD

**Issue by seblucas** [djrobstep/migra#36]
Hi,

This afternoon I was tasked for my day job to review some schema comparison tool for PostgreSQL, yours was part of these tools. To prepare the test I created Alpine based docker images (your docker file is based python3 and the base image is 350MB), I did so and I was able to use migra without any problem with an 94MB image (with Postresql 10.4). 

Are you interested in a PR with this Dockerfile ? 
Do you prefer that I post it directly on Dockerhub ?

Thanks for this tool.

**Comment by djrobstep** [comment]
That would be great, absolutely interested in a PR for this! The current one does seem like an excessive size.

Also interested in any feedback you have, what was the result of your review?

**Comment by djrobstep** [comment]
Solved, closing 👍
