### ISSUE TITLE
Compare schemas/tables in the same database

### ISSUE THREAD

**Issue by YaTree** [djrobstep/migra#38]
Hi.

Is it possible to compare schemas inside one database?
I need it, for example, if I have inheritance tables - and I want to know what is the difference between children or parent and children (it could be when in one schema we need something specific and in another we dont need, but before tables had same structure)

**Comment by djrobstep** [comment]
That's an interesting use case. There's no great way to do this currently on the command line. You should be able to script up something with the API to do this tho. 

Closing this issue for now as I don't see a good way to add this directly as a feature.
