### ISSUE TITLE
Thank you 💖

### ISSUE THREAD

**Issue by vassilevsky** [djrobstep/migra#4]
I have just successfully synced a schema. It was only 3 statements but it was nice to know that they are now 💯% identical ✨

**Comment by djrobstep** [comment]
Awesome! Always delighted to hear from real users, so thank you. Glad it was useful to you

**Comment by ozum** [comment]
Hi,

I haven't used it yet, but it sounds very nice. I'm also developing some open source code generation tools. Especially interested in PostgreSQL. Happy to see such tools for pg. 

If you have time please have a look at [pg-generator](http://www.pg-generator.com) code generating tool. (Although I have written it for node.js, it would be good to have a similar tool for python.)
