### ISSUE TITLE
Postgres temporary schemas

### ISSUE THREAD

**Issue by afonso360** [djrobstep/migra#41]
Hi, I'm seeing a lot of
```sql
drop schema if exists "pg_toast_temp_9";
```
Generated in the migration files. From what i understand these are temporary schemas used by postgres, and are mostly safe to remove if the backend_id is low enough. But it would be nice not to put these, or
put them behind a flag.

A similar thing happens with
```sql
drop schema if exists "pg_temp_11";
```

**Comment by djrobstep** [comment]
Yep we should get rid of these, probably by just fitering out `pg_temp_*` and and `pg_toast_temp_*` from the schema inspection query in https://github.com/djrobstep/schemainspect. I'll create an issue over there regarding this.
