### ISSUE TITLE
Add support for trigger associations

### ISSUE THREAD

**Issue by akeeman** [djrobstep/migra#42]
Functions themselves are handled, but whether triggers are associated with a table is not.

Related queries:
```sql
select * from information_schema.triggers;

create trigger {trigger_name} {action_timing} {event_manipulation} on {event_object_table} for each {action_orientation} {action_statement};

drop trigger if exists {trigger_name} on table {event_object_table};
```

**Comment by djrobstep** [comment]
Hi, thanks heaps for filing this issue! This would be a nice thing to add (only reason it hasn't happened is that I don't use triggers myself).

I'm time-poor at the moment so can't give this immediate attention, but pull requests extremely welcome.

**Comment by djrobstep** [comment]
Initial trigger support has now been added.
