### ISSUE TITLE
Installation on mac fails

### ISSUE THREAD

**Issue by nastil** [djrobstep/migra#46]
Running "pip install migra" on mac produces following error:

Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/_t/ddw221xj6j1d2ypg89jylbg80000gn/T/pip-install-iId86s/sqlalchemy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/_t/ddw221xj6j1d2ypg89jylbg80000gn/T/pip-record-5Nxl3C/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/_t/ddw221xj6j1d2ypg89jylbg80000gn/T/pip-install-iId86s/sqlalchemy/

**Comment by djrobstep** [comment]
Hey, thanks for filing this issue!

Unfortunately I can't reproduce on my mac, so you'll have to give me more information. Could you tell me your:

- macos version?
- pip version?
- python version?
- whether you're in an active virtual environment or not when you're trying to install?

That might help narrow down the problem. In the short term, try upgrading any/all of those things and see if that helps.

**Comment by nastil** [comment]
Hey,
* MacOs 10.13.6 (High Siera)
* pip 10.0.1 from /Library/Python/2.7/site-packages/pip-10.0.1-py2.7.egg/pip (python 2.7)
* Python 2.7.10
* Not in a virtual environment

Should I try to go to python version 3?

**Comment by djrobstep** [comment]
Installing python 3 is probably a good general idea (2 reaches end of life very soon) but migra is tested and works on 2. Using virtual environments is also recommended but not essential.

It seems from some of your error output it's related to sqlalchemy (which is one of migra's dependencies). Do you get the same error when you try to install `sqlalchemy` directly?

**Comment by nastil** [comment]
Ok, "pip3 install migra" did the trick for me, thank you for help!

**Comment by djrobstep** [comment]
All good, glad you got it working!
