### ISSUE TITLE
The output does not include default values of function arguments

### ISSUE THREAD

**Issue by mshahbazi** [djrobstep/migra#49]
Thanks for the great work.

I have a function defined as follows:
`create function my_function(arg1 text, arg2 text default '') returns void`

The migration output drops the default value of the argument and returns the following:
`create function my_function(arg1 text, arg2 text) returns void`

This is sort of problematic since calling `my_function('some value')` works in the source database but raises error in the second one.

**Comment by mshahbazi** [comment]
After digging into the issue, I found out that the issue refers to `schemainspect` package. So I would create a new issue there.

Thanks.

**Comment by bartgras** [comment]
@mshahbazi I'm having similar issue. Did you figure it out or found alternative?

**Comment by djrobstep** [comment]
@bartgras There is a pull request in progress for fixing this: https://github.com/djrobstep/schemainspect/pull/16

It just needs the tests fixed before it can be merged and released. You could:

- use that version temporarily
- help fix the tests
- or wait until the tests get fixed

**Comment by djrobstep** [comment]
Thanks to @mshahbazi this is now solved, closing.
