### ISSUE TITLE
migra $url_a $url_b generates b -> a migration

### ISSUE THREAD

**Issue by micimize** [djrobstep/migra#52]
The docs and readme say the cli command`migra $url_a $url_b` generates the migration __from A to B__, but I'm getting the migration from __from B to A__. I believe I'm using the most recent version, `1.0.1535509978`

**Comment by djrobstep** [comment]
That would be very surprising! Are you sure? Can you give me a reproducible example?

**Comment by micimize** [comment]
Sorry, this was my mistake. Was reading it as "take changes __from A__ and apply them __to B__" instead of "migrate __from schema A to schema B__"

Here's the script I threw together that clarified it for me:
```bash
OUTDATED=migra_a
UPDATED=migra_b

OUTDATED_URL=postgresql://localhost:5432/$OUTDATED
UPDATED_URL=postgresql://localhost:5432/$UPDATED

psql << INIT
create database $OUTDATED;
create database $UPDATED;

\c $UPDATED
create table new_table ();
INIT

echo "
migration from outdated db $OUTDATED to updated db $UPDATED:
"

migra --unsafe $OUTDATED_URL $UPDATED_URL

psql << CLEANUP
drop database $OUTDATED;
drop database $UPDATED;
CLEANUP
```
