### ISSUE TITLE
Support row-level security (RLS) policies

### ISSUE THREAD

**Issue by bfelbo** [djrobstep/migra#53]
We're using migra as the backbone of our deployment flow. However, one crucial issue is that migra does not currently support [row-level security (RLS) policies](https://www.postgresql.org/docs/10/static/ddl-rowsecurity.html). These policies are needed to enjoy all the wonders of Postgres. For instance, it's what enables us to mainly rely on [Postgraphile](https://www.graphile.org/postgraphile/) for our API needs. Do you have any plans to implement RLS?

It seems to me that it should be possible to partially reuse the functionality for finding diffs between functions/grants for finding diffs between policies.

**Comment by djrobstep** [comment]
Hey, it's awesome to hear you're using migra for your deployment flow!

I'd love to hear a bit more about your setup, what you're managing with it, and what your workflow is.

RLS is definitely a feature I'd love to see added, but it's a question of time. `migra` is a 100% spare time labour of love at this point, and while I wish I had more time to work on it, I have a real job and not enough spare time beyond that.

Unless there was dedicated financial support for the project and/or many more external contributors it's never going to get the full attention it deserves, unfortunately.

Of course, pull requests are always welcome, and I try to make time to review these and get them incorporated. A starting point would be to add inspection of RLS information to `schemainspect`.

**Comment by bfelbo** [comment]
Basically, we're building all of our backend functionality (data, API, security, etc.) directly into the Postgres database. We use Postgraphile extensively. Migra is used to manage changes between personal dev DBs, staging DB, beta DB and production DB.

We've coded up some tooling to allow us to easily identify diffs using migra, spin up a test DB, apply the migrations and run unit tests to ensure that everything will migrate successfully and work as intended.

This stack is working wonders for us and we see a lot of potential in this kind of approach going forward. Right now we're a 2-man team so we have to really prioritize and get our product off the ground, but I'm hoping we'll be able to help out with migra soon. Thanks for the heads up on where to start.

**Comment by djrobstep** [comment]
Sounds like a great setup, and it's cool to hear you're using migra to manage the changes and increase the testability.

All the best with your product! Look forward to hopefully collaborating in the future.

I'll leave this issue open until we get around to tackling RLS.

**Comment by bfelbo** [comment]
@djrobstep I can't find your contact info. Can you write me on my email at https://bfelbo.com/? I'd like to discuss a bit how we could collaborate to solve this issue.

**Comment by djrobstep** [comment]
An initial version of this is now implemented. Could be more efficient (does drop-and-recreate for all changed policies instead of `alter policy...` but it seems to pass some basic tests.

Let me know if you run into any bugs or edge cases.

**Comment by bfelbo** [comment]
Perfect, thanks! We'll check it out right away.

**Comment by djrobstep** [comment]
Closing this one for now for the sake of cleanup, can tackle any further related bugs/development in separate issues
