### ISSUE TITLE
Supporting stored function language PL/Python

### ISSUE THREAD

**Issue by bfelbo** [djrobstep/migra#55]
We’d like to use migra to diff some of our stored functions that use the [PL/Python language](https://www.postgresql.org/docs/10/plpython.html). This language is not currently supported by migra. How hard is it to add basic support for it?

I’m thinking one could simply treating the entire PL/Python code within the stored function as a text blob and diff that. It’s not clear to me why migra would need to handle PL/Python any different from the currently supported procedural languages.

**Comment by djrobstep** [comment]
It's your lucky day, pl/python functions should already be supported! `schemainspect` examines all functions whose language isn't "c" or "internal". I gave it a go just now and it seemed to work with a basic plpython3u function. 

I've never used pl/python functions for anything serious tho so I'd be interested to know if you run into any issues with it.
