### ISSUE TITLE
"PARTITION BY" not recognized as diff.

### ISSUE THREAD

**Issue by Glupschauge** [djrobstep/migra#60]
When comparing following schemas, "PARTITION BY" is not recognized as a diff if it is added to an already existing table.

schema a: 
`CREATE TABLE measurement (
    city_id         int not null,
    logdate         date not null,
    peaktemp        int,
    unitsales       int
);
`

schema b: 
`CREATE TABLE measurement (
    city_id         int not null,
    logdate         date not null,
    peaktemp        int,
    unitsales       int
) PARTITION BY RANGE (logdate);`

Following command shows no difference.
 `migra --unsafe postgresql:///schema_a postgresql:///schema_b` 

I know this is a special case, however I would be grateful if this problem could be fixed.

**Comment by djrobstep** [comment]
Hey, thanks for filing this issue and testing out the new partitioning support! Indeed `migra` doesn't yet handle this case correctly. I'll endevour to fix.

**Comment by djrobstep** [comment]
This is fixed now as of the latest release, tables that move from partitioned->non-partitioned (or vice versa) are dropped and recreated. Let me know how it works for you.

**Comment by djrobstep** [comment]
Closing this for now, feel free to create new issues for any problems encountered.
