### ISSUE TITLE
Recreating the indexes

### ISSUE THREAD

**Issue by hoducha** [djrobstep/migra#61]
When I run the migra with --unsafe option, it always generate a file that includes the SQL for recreating the indexes like this:
```sql
drop index if exists "public"."users_id_pk";

CREATE UNIQUE INDEX users_id_pk ON users USING btree (id);
```
Any ideas?

**Comment by djrobstep** [comment]
Can't reproduce this, do you have a minimal example of two databases where this occurs?

**Comment by djrobstep** [comment]
Closing this for now, feel free to reopen if the problem continues

**Comment by akeeman** [comment]
Same problem here...

**Comment by djrobstep** [comment]
I can't do anything without a reproducible test case, can you provide one?
