### ISSUE TITLE
Why drop functions with cascade when they can be replaced?

### ISSUE THREAD

**Issue by bfelbo** [djrobstep/migra#65]
Migra by default does:

```
drop function if exists my_schema.my_function cascade;
CREATE OR REPLACE my_schema.my_function()
    RETURNS tango.user_private_readonly
    LANGUAGE sql
    STABLE SECURITY DEFINER
    AS $function$
        ...
    $function$
;
```

This causes all sorts of errors. The cascade will drop other necessary functions/policies etc. and without cascade the drop function will fail. Why is the `drop function` statement added when the function is replaced fine without it?

**Comment by djrobstep** [comment]
The latest release makes migra do replaces where it can and leave off the drop statements where not necessary. 

I'm yet to check how this behaves with RLS dependencies.
