### ISSUE TITLE
RLS does not identify correct policy (finds DELETE instead of UPDATE)

### ISSUE THREAD

**Issue by bfelbo** [djrobstep/migra#67]
I created the following policy modifying the `UPDATE` response, but migra finds `DELETE`. This could cause serious security/privacy issues if overlooked. 

**SQL run**
```
CREATE POLICY update_gamer ON my_schema.my_table FOR UPDATE TO gamer USING ((user_id = my_schema.current_user_id()));
```

**Migra diff**
```
create policy "update_gamer"
on my_schema.my_table
as permissive
for delete
to gamer
using (user_id = my_schema.current_user_id());
```

**Comment by djrobstep** [comment]
This should be fixed with the latest `schemainspect` release, let me know if you have any further problems.

**Comment by bfelbo** [comment]
Great, thanks a lot!
