### ISSUE TITLE
Problem with line breaks under Windows

### ISSUE THREAD

**Issue by aszentpeteri** [djrobstep/migra#71]
Dear djrobstep,

We have the same issue like in that issue: https://github.com/djrobstep/migra/issues/15 . But I found the conditions to reproduce it.

Technical details:
-    Windows 10 command line
-    with --unsafe option
-    I run the generated script with DBeaver 5.2.4

What I noticed is that the output of migra contains an extra CR (\r) for every line end in the functions. Originally in the database we have CRLF (\r\n) on the end of the lines, but with the script it's like CR CRLF (\r \r\n).

I'm trying to find a workaround, but it would be nice, if you could correct this, when you have time.

Thank you!

I attached a file containing one of the original functions and the generated pair of it.
[migra_bug_example.txt](https://github.com/djrobstep/migra/files/2749220/migra_bug_example.txt)

_Originally posted by @aszentpeteri in https://github.com/djrobstep/migra/issues/15#issuecomment-453471244_

**Comment by djrobstep** [comment]
I cannot reproduce this. As far as I can tell migra reproduces the line endings accurately from what is in the database. Happy to reopen with some more specifics about how migra gets it wrong.

**Comment by h0gar** [comment]
Had the same problem. Was convinced the problem was coming from migra, but it actually came from the generated SQL file used for the migration. Make sure you don't have CR characters in that file.
