### ISSUE TITLE
Migra does not detect row level security being enabled for a table

### ISSUE THREAD

**Issue by bfelbo** [djrobstep/migra#72]
Migra does not dump `ALTER TABLE mytable ENABLE ROW LEVEL SECURITY`. This is critical because without it, all row level security policies are ignored and the users can access/update/insert/delete all the different rows in the table!

**Comment by djrobstep** [comment]
Are you sure? It should be emitting the enable statements. 

It works OK in the tests and in the example I tried just now.

**Comment by djrobstep** [comment]
@bfelbo is this still an issue?

**Comment by bfelbo** [comment]
I'm sorry - I completely missed this! I've tried reproducing it again, but I can't anymore so it seems to be fixed! :)
