### ISSUE TITLE
Triggers on other schemas are returned when --schema parameter is used

### ISSUE THREAD

**Issue by capsh** [djrobstep/migra#73]
When running migra with a specific schema named, I've found that all the triggers on the database are included in the comparison, even though they are not on tables belonging to the schema I've chosen to compare. This obviously clutters up the migration script quite a bit.

From [PostgreSQL documentation](https://www.postgresql.org/docs/9.2/infoschema-triggers.html):
"Triggers in PostgreSQL have two incompatibilities with the SQL standard that affect the representation in the information schema. First, **trigger names are local to each table in PostgreSQL, rather than being independent schema objects**. Therefore there can be duplicate trigger names defined in one schema, so long as they belong to different tables."

Is the fact that they are not independent schema objects the reason for this?

**Comment by djrobstep** [comment]
I've recently made changes to how trigger names are tracked, to track them per table. Let me know if the latest version fixes this for you.

**Comment by djrobstep** [comment]
This is fixed as of the latest `schemainspect` release.
