### ISSUE TITLE
Custom characters in table names

### ISSUE THREAD

**Issue by jan-swiecki** [djrobstep/migra#76]
Hi,

First of all - thank you for this awesome product! I was looking for such tool for years. It is so obvious to have such tool that I was scratching my head during the years and asked myself why nobody implemented this in any database. In my current project where I have more freedom of choice I thought of writing my own SQL diff tool, but you saved me:).

Regarding this bug/issue, consider the following schema:

```SQL
CREATE TABLE "users" (
  "id" BIGINT PRIMARY KEY NOT NULL,
  "username" VARCHAR NOT NULL UNIQUE
);

CREATE TABLE "companies" (
  "id" BIGINT PRIMARY KEY NOT NULL,
  "name" VARCHAR
);

CREATE TABLE "companies_users(by_field=companies.owners)" (
  "companies_id" BIGINT NOT NULL REFERENCES "companies" ("id") ON DELETE CASCADE,
  "users_id" BIGINT NOT NULL REFERENCES "users" ("id") ON DELETE CASCADE,
  PRIMARY KEY ("companies_id", "users_id")
);
```
Then let's say `a` database has above schema and `b` database is empty.

    $ migra --unsafe postgres://localhost/b postgres://localhost/a
    (...)
    alter table "public"."companies_users"(by_field=companies.owners) add constraint "companies_users"(by_field=companies.owners)_pkey PRIMARY KEY using index "companies_users"(by_field=companies.owners)_pkey;

    alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

    alter table "public"."companies_users"(by_field=companies.owners) add constraint "companies_users"(by_field=companies.owners)_companies_id_fkey FOREIGN KEY (companies_id) REFERENCES companies(id) ON DELETE CASCADE;

    alter table "public"."companies_users"(by_field=companies.owners) add constraint "companies_users"(by_field=companies.owners)_users_id_fkey FOREIGN KEY (users_id) REFERENCES users(id) ON DELETE CASCADE;
    (...)

As you see migra can't handle such custom table names and gives wrong alter table **"public"."companies_users"(by_field=companies.owners)** which gives errors such as:

    ERROR:  syntax error at or near "="
    LINE 1: create table "public"."companies_users"(by_field=companies.o...
                                                            ^

I like those custom characters because multiple many to many tables between same two tables such as `users` and `companies` are hard to distinguish. Currently I generate all schema from ORM model where I have multiple ManyToMany annotations and connections, so it gets messy in SQL schema file.

Let me know what you think.

**Comment by jan-swiecki** [comment]
You could argue that that `(` nad `)` are not keyword characters, but anything enclosed in `"` quotes beside zero-character should be supported.

See this https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS:

> There is a second kind of identifier: the delimited identifier or quoted identifier. It is formed by enclosing an arbitrary sequence of characters in double-quotes ("). (...) Quoted identifiers can contain any character, except the character with code zero.

I understand this is not priority issue. For now I will use `$` character (`$by_field=...` instead of `(by_field=...)`).

**Comment by djrobstep** [comment]
First, thank you for the encouraging words, I'm glad you like using it!

As for the bug itself, this should be fixed as of the latest release, let me know if you run into any problems.
