### ISSUE TITLE
Recreating the indexes with where clause

### ISSUE THREAD

**Issue by akeeman** [djrobstep/migra#79]
I noticed that indexes are recreated in version 1.0.1552220361 (currently latest on pypi), when the index contains a where clause.

Steps for recreation:
1. Dump this in database `a` and `b`:

```sql
create table "public"."foo" (
    "id" integer,
    "value" integer
);

CREATE INDEX foo_idx ON public.foo USING btree (id) WHERE (id > 10);
```

2. Then run migra to get the differences from `a` to `b`: 
```bash
$ migra postgresql:///a postgresql:///b --unsafe
```

Expected result: 
No differences

Actual result:

```sql
drop index if exists "public"."foo_idx";

CREATE INDEX foo_idx ON public.foo USING btree (id) WHERE (id > 10);
```

**Comment by djrobstep** [comment]
Just ran this now and got no differences in the output.

Can you tell me what versions you're using of:

- migra
- schemainspect
- python
- postgres
- operating system

That will help me investigate.

**Comment by akeeman** [comment]
`schemainspect.pg.obj.InspectedIndex::partial_predicate` is unequal

**Comment by akeeman** [comment]
* migra: 1.0.1552220361
* schemainspect: 0.1.1552220105
* python: Python 3.7.0b3
* postgres: 10.6
* operating system: linux mint 19.1 (ubuntu bionic)

**Comment by akeeman** [comment]
It seems that I didn't supply accurate reproduction steps. Let me try that again.

**Comment by akeeman** [comment]
I find it hard to come up with a simplified example that shows what i'm experiencing. The actual case still is that the location numbers in `schemainspect.pg.obj.InspectedIndex::partial_predicate` differ.

Just me being curious: why is `partial_predicate` compared, and `definition` is not in `schemainspect.pg.obj.InspectedIndex::__eq__`? It seems that `partial_predicate` is the underlying definition of the where clause, and that the `location` parts given in it are character positions of the start of the token. The where clause is also given in `schemainspect.pg.obj.InspectedIndex::definition`, but the two `definition` values _are_ the same.

Maybe swap [this line](https://github.com/djrobstep/schemainspect/blob/master/schemainspect/pg/obj.py#L364) for `self.definition == other.definition,`?

**Comment by benjolitz** [comment]
Also affected by this for a while.

My deployment code is architected to do a fresh install of migra each time from PyPI. 

Both partial unique indices I have defined are always dropped/created every time I compare identical schemas between a docker bootstrapped fresh postgres install and an RDS deployment.
