### ISSUE TITLE
Correct ordering of function changes aka function dependency tracking

### ISSUE THREAD

**Issue by djrobstep** [djrobstep/migra#8]
Postgres tracks view dependencies (view -> view,   view -> function) but not function dependencies (function -> function, function -> view). Nevertheless, when creating functions, PostgreSQL errors out when creating functions whose dependencies don't exist.

This means it's not possible for `migra` to determine the correct ordering of function changes, a frustrating limitation for those who make use of user defined functions (such as myself).

It would seem the only way to fix this is for Postgres to either: 

- allow creation of functions with missing dependencies, deferring the checking until eg the end of the transaction
- track function dependencies so we can determine the correct creation/drop ordering (probably a lot of work for the postgres devs)

At the moment there seems to be no workaround other than tweaking one's setup script to add the dependencies manually, which is very tedious.

How to solve this?

**Comment by djrobstep** [comment]
Added some code to do this by simply looking for the name of the dependency within the function definition. Fails if that name is used to refer to something else or if there is overloading of function names. So not ideal but works well in 90% of cases.

**Comment by johto** [comment]
> allow creation of functions with missing dependencies, deferring the checking until eg the end of the transaction

This can be achieved by simply SETing check_function_bodies to FALSE.  That's what pg_dump does, for example.  However the checks are deferred until the next time the function is executed, and AFAIK there's no good way to force a check at the end of a transaction.  But I find the end-of-transaction check to have only dubious value in the first place; what if the source database had a broken function?  Wouldn't we still want to make the two databases identical?

**Comment by djrobstep** [comment]
Hard agree on all that, the function body check is more trouble than it is worth. We should modify `migra` to turn it off, and simply not do the check.

**Comment by djrobstep** [comment]
Latest release of migra now sets `check_function_bodies` to off when adding functions. This should solve this problem.
