### ISSUE TITLE
Diff created for partitioned table is incomplete

### ISSUE THREAD

**Issue by iolbr** [djrobstep/migra#81]
Hi, 
performed a diff between an devlopment database and an empty test system. 
Partitioned table was correctly identified and create statements for partitions were generated but partition name is missing:

create table "public"."z" (...) partition by LIST (oder_year);
create table partition of "public"."z" FOR VALUES IN ('2014');

expected :
create table **z_201901** partition of "public"."z" FOR VALUES IN ('2014');

Best regards,
Ingo

**Comment by djrobstep** [comment]
Thanks a lot for filing this issue! Has taken me a while to get to it but this is fixed now. Let me know how it goes, and if you have any troubles, feel free to reopen.
