### ISSUE TITLE
Enum type that has a value added fails to migrate

### ISSUE THREAD

**Issue by BadPirate** [djrobstep/migra#83]
Repro:

- DB-A and DB-B are identical, and have an Enum type described
- Enum is used as the type for one of the columns in a table
- Alter the enum (add another value) to DB-A

Expectation:

- Upgrade schema has an alter for adding the missing type

Actual:

- Upgrade schema tries (and fails) to drop and re-add the enum

**Comment by strigona-worksight** [comment]
I just got bit by this the other day. Took a bit of head scratching to figure out what wen wrong.

**Comment by deem0n** [comment]
The same thing (DROP/CREATE TYPE) happens if you delete item from the ENUM TYPE as well.
migra-1.0.1592301305

**Comment by djrobstep** [comment]
I've reworked the enum logic a bit. The trouble with supporting `alter type`s, is that alter doesn't support all the ways an enum's values can possibly change. PG12 now supports alters in transactions but still retains these limitations, and even the supported alters (eg inserting values before other values in the enum order has (mild) performance implications.

So I've implemented a change algorithm as follows. If enum e has its values changed, then:

- Rename e to something else (say e_renamed)
- Create a new enum e with the new values
- Cast all columns of type e_renamed to e (`alter type ... using e_renamed::text::e`)
- Drop the now unused e_renamed enum

This is slightly slicker than the old drop-and-recreate approach where each field using that enum temporarily became a text column. And it means that any possible change to the enum values is supported.

I'm going to close this for now, but feel free to reopen if there's any further issues with this, or if there's better ways to support enum changes that I don't know about.
