### ISSUE TITLE
When joining views, migra explicitly writes out all the table variables instead of table.*

### ISSUE THREAD

**Issue by bfelbo** [djrobstep/migra#86]
It can be useful to have views that always have all columns using `a.*` such that if more variables are added later to that table `a`, it'll also be added to the view. However, migra will list out all the variables in the migration, which defeats this purpose. See the code examples below:

```
CREATE OR REPLACE my_view AS
    SELECT
    a.*,
    b.something,
   FROM a
   LEFT JOIN b.id = a.id;
```
becomes
```
CREATE OR REPLACE my_view AS
    SELECT
    a.variable1,
    ...,
    a.variableN,
    b.something,
   FROM a
   LEFT JOIN b.id = a.id;
```

**Comment by jasongi-actu** [comment]
Postgres writes out all the variables at table creation time, so doing this doesn't really make sense - they are equivalent statements. Here is an example of what I mean

Create a table and a view on the table
`
jgiancono=# create table xd(x int);
CREATE TABLE
jgiancono=# create view y as (select xd.* from xd);
CREATE VIEW
jgiancono=# \d y
                  View "public.y"
 Column |  Type   | Collation | Nullable | Default 
--------+---------+-----------+----------+---------
 x      | integer |           |          | 
`
Add a column to the table
`
jgiancono=# alter table xd add column z int;
ALTER TABLE
jgiancono=# \d y
                  View "public.y"
 Column |  Type   | Collation | Nullable | Default 
--------+---------+-----------+----------+---------
 x      | integer |           |          | 
`
In order for the view to get the new column, you would need to recreate it.

**Comment by bfelbo** [comment]
Oh really, that's surprising to me. I guess we'll then have to create a script that recreates the views every time a schema change is applied to an underlying table.
