### ISSUE TITLE
migra ignores dependent policies while dropping and re-creating views

### ISSUE THREAD

**Issue by TimoStolz** [djrobstep/migra#87]
Lets say
- there are two views V1 and V2
- there is a policy P
- V2 depends on V1
- P depends on V2

Now assume
- V1 must be recreated.
- Since some columns were dropped, `create or replace` is impossible. Instead, we need to `drop view v2`, then we need to `drop view v1`, afterwards we need to `create view v1` with another set of columns, and then finally, we need to `create view v2` again.

What went wrong?
- the migrations fails with an error saying that P depends on V2.

What is the expected behavior?
- in the beginning, migra should `drop policy P` before `drop view v2`
- in the end, migra should `create policy P` after `create view v2`

**Comment by djrobstep** [comment]
I believe this is now solved. If this is not the case, feel free to reopen this issue.
