### ISSUE TITLE
Comparing remote databases: credentials.

### ISSUE THREAD

**Issue by ru5t** [djrobstep/migra#88]
Comparing remote databases. Don't see [option](https://djrobstep.com/docs/migra/options) to pass credentials.
Command looks like:
```
migra postgresql://172.27.203.34/fiscabil postgresql://172.27.203.34/fiscabil_test
```
And as result I have exception:
```
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) fe_sendauth: no password supplied
```
Is there way to pass username/password?

**Comment by ru5t** [comment]
My bad. Connection string can have user and password:
`migra postgresql://username:passwd@host/database`

**Comment by roblevy** [comment]
This turned out to be pretty useful to me (an ignoramus about connecting to Postgres on the command line.) Possible link in the docs to something which shows you how to flesh out the `postgres:///a` in the examples?

**Comment by djrobstep** [comment]
Yeah good call. A general guide to database URIs would be helpful to a lot of people I reckon
