### ISSUE TITLE
Functions continue to show in diff even after application.

### ISSUE THREAD

**Issue by tim-field** [djrobstep/migra#89]
I have an application that has a lot of stored procedures.  When I diff my dev and testing databases, I see the same few functions showing each time. 

The migration script is applied, and yet they will show again.  I'm comparing two databases running form the same server, which is running postgres version 11.3

Anyone else seen the behaviour? An example;

```
CREATE OR REPLACE FUNCTION foo.project_associated_project_company_name(the_project project)
 RETURNS character varying
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'foo', 'foo_utils', 'public'
AS $function$
  select comp.name
  from project proj inner join company comp on comp.id = proj.company_id
  where proj.id = the_project.associated_project_id
$function$
;
```

**Comment by bfelbo** [comment]
We experience this as well. Interestingly, it stops happening if you dump the function using pg_dump and then apply the dumped function to the databases. This is a rather cumbersome fix though.

**Comment by tim-field** [comment]
Hmm thanks for the top @bfelbo even doing this I'm still seeing the function

**Comment by djrobstep** [comment]
Closing this for now - I cannot verify that this is an actual bug and not simply a matter of line endings not matching

**Comment by h0gar** [comment]
Had the same problem. Was convinced the problem was coming from migra, but it actually came from the generated SQL file used for the migration. Make sure you don't have CR characters in that file.

**Comment by tim-field** [comment]
Yes it was line endings that caused this for me

**Comment by tabeckers** [comment]
When piping the diff to a psql command no CRLF issues arise.

`migra ... ... | psql ...`
