### ISSUE TITLE
Support "identity columns"

### ISSUE THREAD

**Issue by djrobstep** [djrobstep/migra#9]
`migra` is going to need changes to fully support postgres 10's new features.

In particular:

- [Identity columns](https://blog.2ndquadrant.com/postgresql-10-identity-columns/)
- [Native partitioning](https://wiki.postgresql.org/wiki/New_in_postgres_10#Native_Partitioning)

The bulk of the work will be making changes to schemainspect to detect the identity column and partitioning information.

**Comment by djrobstep** [comment]
Native partitioning is implemented, but not identity columns just yet

**Comment by bmintz** [comment]
I opened a draft pull request as djrobstep/schemainspect#29 which starts to implement identity columns. Please take a look.

**Comment by djrobstep** [comment]
Hello, thank you so much for contributing this! Been super busy and had no spare time to review properly yet, but will do so as soon as I can.

**Comment by tolmacevalexandr** [comment]
I opened another pull request as https://github.com/djrobstep/schemainspect/pull/43
My approach differs from the one suggested earlier by Io Mintz. I added identity as a column property.

**Comment by djrobstep** [comment]
This is now resolved, using the PR from @tolmacevalexandr plus some additional changes and tests.

Let me know how well it works for you.
