### ISSUE TITLE
UNLOGGED table is not supported

### ISSUE THREAD

**Issue by gajus** [djrobstep/migra#91]
See UNLOGGED flag

https://www.postgresql.org/docs/11/sql-createtable.html

If UNLOGGED table is being referred by a newly created table and UNLOGGED flag is not added, then create table command fails because LOGGED tables cannot refer to UNLOGGED tables.

**Comment by djrobstep** [comment]
This is now supported in the latest release - migra detects unlogged tables and changes in logged/unlogged status. Let me know how it works for you.
