### ISSUE TITLE
default exit code confusing

### ISSUE THREAD

**Issue by micimize** [djrobstep/migra#98]
exit 2 seems to be the default for successful output, which is confusing because [non-zero exits are errors](http://tldp.org/LDP/abs/html/exitcodes.html). This means I can't `set -e` with `migra`.

https://github.com/djrobstep/migra/blob/f823fdc036e11237ab5ec319fa33d013c652b909/migra/command.py#L92-L96

**Comment by djrobstep** [comment]
The intent here is to match the behaviour of the `diff` command, which returns 0 if files match, and non-zero if they don't.

I don't remember now why I made it return 2 specifically rather than 1 (as diff does) for non-matching files, perhaps we should change this in a future release.

**Comment by micimize** [comment]
ah, ok, hmm. Yeah, maybe a flag to invert the flags... but I'll close this as it's a design decision and I think the real take-away is [not to trust in `set -e`](https://stackoverflow.com/questions/19622198/what-does-set-e-mean-in-a-bash-script)

**Comment by meglio** [comment]
So maybe `1` was for errors?
