### ISSUE TITLE
Lack of support for inheritance

### ISSUE THREAD

**Issue by benjolitz** [djrobstep/migra#99]
I found a use case for postgres table inheritance, namely replacement for the following view:
```
CREATE VIEW entity_bindings AS
    SELECT entity_type, entity_id
    FROM entity_bindings_A
    UNION ALL
    SELECT entity_type, entity_id
    FROM entity_bindings_B
    UNION ALL
    SELECT entity_type, entity_id
    FROM entity_bindings_c
```

This is due to views not being aware of the CONSTRAINT that ensures only one `entity_type` is allowed per table. Table inheritance allows for that. My goal is to preserve foreign key constraints.

So I implemented the following sample (no foreign key to simplify)

```
CREATE TABLE entity_bindings (
    id BIGSERIAL,
    entity_type TEXT NOT NULL,
    entity_id BIGINT NOT NULL
);
CREATE TABLE entity_bindings_A (
    CONSTRAINT "entity_type must be A" CHECK("entity_type" = 'A'),
    UNIQUE("entity_id", "entity_type")
) INHERITS (entity_bindings)
;
CREATE TABLE entity_bindings_B (
    CONSTRAINT "entity_type must be B" CHECK("entity_type" = 'B'),
    UNIQUE("entity_id", "entity_type")
) INHERITS (entity_bindings)
;
CREATE TABLE entity_bindings_C (
    CONSTRAINT "entity_type must be C" CHECK("entity_type" = 'C'),
    UNIQUE("entity_id", "entity_type")
) INHERITS (entity_bindings)
;
```

Expected behavior:

- Migra checks `pg_catalog.pg_inherits` to see if a table is inherited, creates the table then does an `ALTER TABLE $table_name INHERITS $table_parent`

What currently happens:

- Migra generates the parent and child tables but without `INHERITS (...)` in the `CREATE TABLE` statements and there is no `ALTER TABLE $table_name INHERITS $table_parent`

Currently I am using a `DO` block to heal the tables after a migration using
```
DO
$do$
DECLARE row RECORD;
BEGIN
   FOR row IN SELECT child_table, parent_table, (row_number() over ()) AS index FROM (
    VALUES
        ('entity_bindings_A', 'entity_bindings'),
        ('entity_bindings_B', 'entity_bindings'),
        ('entity_bindings_C', 'entity_bindings')
) tmp(child_table, parent_table)
   ORDER BY index ASC
   LOOP
   IF NOT EXISTS (
        SELECT 1
        FROM   pg_catalog.pg_inherits
        WHERE  inhrelid = (row.child_table)::regclass
    ) THEN
      EXECUTE 'ALTER TABLE ' || row.child_table ||  ' INHERIT ' || row.parent_table;
   END IF;
   END LOOP;
END
$do$;
;
```

**Comment by djrobstep** [comment]
This should be fixed now, as of the latest release. If not please feel free to reopen
